spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lsd2
    username: root
    password: txt1995
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
error:
  errorMessage:
    LSD_01:
      err_vn: Email has been used !!
      err_us: Email đã được sử dụng !!
    LSD_02:
      err_vn: Phone number has been used !!
      err_us: Số điện thoại đã được sử dụng !!
